Fix testHistory
Test broke because of an extra space in output:

expected:</bin/sh -c #(nop) []CMD ["sh"]> but was:</bin/sh -c #(nop) [ ]CMD ["sh"]>

I think this was because busybox:latest was updated.